version: '3.6'
services:
  kong:
    container_name: supabase-kong
    build:
      context: ./kong
    environment:
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PLUGINS: request-transformer,cors,key-auth,http-log
      KONG_DNS_ORDER: LAST,A,CNAME
    ports:
      - 8000:8000/tcp
  auth:
    container_name: supabase-auth
    image: supabase/gotrue:latest
    environment:
      GOTRUE_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_API_HOST: auth
      PORT: 9999
      GOTRUE_DISABLE_SIGNUP: 'false'
      GOTRUE_SITE_URL: http://localhost:8000
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: GOTRUE_SMTP_USER
      GOTRUE_SMTP_PASS: GOTRUE_SMTP_PASS
      GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
      GOTRUE_MAILER_AUTOCONFIRM: 'false'
      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: Confirm Your Signup
      GOTRUE_MAILER_SUBJECTS_INVITE: You have been invited
      GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: Your Magic Link
      GOTRUE_MAILER_SUBJECTS_RECOVERY: Reset Your Password
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
      - mail
  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:nightly-2021-03-05-19-03-d3a8b5f
    depends_on:
      - db
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public, storage
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:latest
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      HOSTNAME: localhost
      # Disable JWT Auth locally. The JWT_SECRET will be ignored.
      SECURE_CHANNELS: 'false'
      JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  storage:
    image: supabase/storage-api:v0.9.1
    depends_on:
      - db
      - rest
    restart: on-failure
    environment:
      ANON_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoiYW5vbiJ9.36fUebxgx1mcBo4s19v0SzqmzunP--hm_hep0uLX0ew
      SERVICE_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI
      PROJECT_REF: bjwdssmqcnupljrqypxz # can be any random string
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      PGOPTIONS: '-c search_path=storage'
      FILE_SIZE_LIMIT: 52428800
      REGION: us-east-1 # region where your bucket is located
      GLOBAL_S3_BUCKET: supa-storage-testing # name of s3 bucket where you want to store objects
      # AWS_ACCESS_KEY_ID: replace-with-your-aws-key
      # AWS_SECRET_ACCESS_KEY: replace-with-your-aws-secret
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/data/storage
  db:
    container_name: supabase-db
    build:
      context: ./postgres
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:stable
    ports:
      - 9000:9000
