blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/inlang/monorepo/discussions
    about: Have an idea for a new feature? Let us know here.
  - name: Question
    url: https://github.com/inlang/monorepo/discussions
    about: Please ask and answer questions here.
  - name: Discord Chat
    url: https://discord.gg/WUhmpYhq
    about: Come chat with us on discord.
