blank_issues_enabled: true
contact_links:
  - name: inlang.com (website)
    url: https://github.com/opral/inlang.com
    about: Issue tracker for inlang.com
  - name: Sherlock (VSCode Extension)
    url: https://github.com/opral/inlang-sherlock
    about: Issue tracker for Sherlock.
  - name: Fink
    url: https://github.com/opral/inlang-fink
    about: Issue tracker for Fink.
  - name: Ninja i18n GitHub action
    url: https://github.com/opral/ninja-i18n-action
    about: Issue tracker for Ninja i18n GitHub action.
  - name: Inlang Message SDK
    url: https://github.com/opral/inlang-message-sdk
    about: Issue tracker for Inlang Message SDK.
  - name: Lix SDK
    url: https://github.com/opral/lix-sdk
    about: Issue tracker for Lix SDK.
