name: Publish ide extension

on:
  workflow_dispatch:

  push:
    paths:
      - "inlang/source-code/ide-extension/package.json"
    branches:
      - main

jobs:
  vs-code-marketplace:
    runs-on: ubuntu-latest
    environment: vscode-marketplace
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: pnpm install

      - name: Install Doppler CLI for env variables
        uses: dopplerhq/cli-action@v2

      - name: Build
        run: doppler run -- pnpm build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - name: Test
        run: doppler run -- pnpm test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - name: Build VSCode extension package
        run: doppler run -- pnpm --filter vs-code-extension package
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - name: Publish to VSCode Marketplace
        run: pnpm --filter vs-code-extension run publish
        working-directory: ./inlang/source-code/ide-extension
        env:
          VSCE_TOKEN: ${{secrets.VSCODE_MARKETPLACE_TOKEN}}
